env: "local" #dev, prod, local
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8081"
  timeout: 4s
  idle_timeout: 60s
kafka:
  producers:
    brokers:
      - "172.19.0.3:29092"
    topic: "ush.events.local"